
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8B0734D6A6E1F617C098BDA525B3131C'
    
_lr_action_items = {'CODE':([8,],[9,]),'IP':([0,],[1,]),'-':([1,4,],[4,5,]),'COMMAND':([7,],[8,]),'TIME':([6,],[7,]),'DATE':([5,],[6,]),'$end':([2,3,9,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[2,]),'line':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> line','start',1,'p_start','PLYlog.py',39),
  ('line -> IP - - DATE TIME COMMAND CODE','line',7,'p_line','PLYlog.py',43),
]
